[package]
name = "torrus_storage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
torrus_core = {path = "../torrus_core"}
anyhow = "1"

